# Generated by Django 5.1.1 on 2024-09-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_address_remove_client_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
