# Generated by Django 5.1.1 on 2024-09-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('validated', 'Validated'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('dending', 'Pending')], default='delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
