# Generated by Django 5.1.1 on 2024-09-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivered_at_order_is_delivered_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('validated', 'Validated'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('dending', 'Pending')], default='dending', max_length=20),
        ),
    ]
