# Generated by Django 5.1.1 on 2024-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('validated', 'Validated'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('dending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
